### ISSUE TITLE
Feature request redux support

### ISSUE THREAD

**Issue by teameh** [Limenius/ReactBundle#1]
Hi there, 

Nice work! I was playing around with the bundle and it works pretty well. 

I noticed the original React on Rails repo features [Redux](https://github.com/shakacode/react_on_rails#redux) integration as well. I was wondering if you were already working on it. Otherwise, maybe I could be of any help implementing it :)

**Comment by nacmartin** [comment]
Thanks! 
Sure, if you want to do it, just go for it! But, if I recall correctly, what React on Rails does with Redux is code generation. At the moment we don't have code generation. I don't know if it would be a good idea, it would probably... but has to be defined what would generate and from what data.

Anyways, what we have is, [at the sandbox](https://github.com/Limenius/symfony-react-sandbox), an example without using Redux, and it would be cool to have another, or the same but rewritten, with Redux. But then it should go in the sandbox, that acts as a boilerplate project with examples.

What do you have in mind? a generator? an example with Redux?

**Comment by teameh** [comment]
Cool!

>  if I recall correctly, what React on Rails does with Redux is code generation.

I think they introduced more stuff in [v4 3.0.0 - 2016-02-15](https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md#added)

> Added helper redux_store and associated JavaScript APIs that allow multiple React components to use the same store. Thus, you initialize the store, with props, separately from the components.

https://github.com/shakacode/react_on_rails#redux_store

> `redux_store(store_name, props = {})`
> - **store_name:** A name for the store. You'll refer to this name in 2 places in your JavaScript:
>   1. You'll call `ReactOnRails.registerStore({storeName})` in the same place that you register your components.
>   2. In your component definition, you'll call `ReactOnRails.getStore('storeName')` to get the hydrated Redux store to attach to your components.
> - **props:**  ReactOnRails takes care of setting up the hydration of your store with props from the view.

It would be cool if it would be added to the twig service as well.

**Comment by nacmartin** [comment]
Ah, I see. If I understood it correctly, the heavy work is done in the npm package of React on Rails, as the helper is only rendering a tag. https://github.com/shakacode/react_on_rails/blob/master/app/helpers/react_on_rails_helper.rb#L103-L114
To me is a nice addition, yes, if you want to work on it, go ahead.

**Comment by teameh** [comment]
:+1: 

I've added some things: https://github.com/Limenius/ReactBundle/pull/3

> Ah, I see. If I understood it correctly, the heavy work is done in the npm package of React on Rails, as the helper is only rendering a tag. 

Yes, and populating the store before sending it off to phpExecJs: 
https://github.com/tiemevanveen/ReactBundle/commit/980fb23a8cc389586cf6e323059c28388ceb824b#diff-784aede647177bc5132814b961272493R90

**Comment by teameh** [comment]
:+1:
