### ISSUE TITLE
True clientside rendering doesn't need PHPExecJS-runtime (node,V8)

### ISSUE THREAD

**Issue by pamuche** [Limenius/ReactBundle#12]
I've dived a little bit into the code and didn't find a quick posibility to entirely disable serverside rendering. If I deploy my code to a server without V8 or node and enable only clientside-rendering PHPExecJS still needs a runtime for serverside rendering. 

Is it possible to disable Serverside rendering entirely

Did I miss something? Where would you implement such thing?

**Comment by nacmartin** [comment]
You are right. It was not actually used, but in the construction of the object, PhpExecJs is autodetecting the available runtimes and failing if it can't find any. I have fixed this in this bundle, so now it only constructs PhpExecJs when you first use it. Thanks for reporting!
