### ISSUE TITLE
Be able to pass an array to the twig tag `props`

### ISSUE THREAD

**Issue by nacmartin** [Limenius/ReactBundle#2]
Right now we have to pass to the Twig tag a JSON serialized string with the props. It would be nice to be able to pass an array too.

**Comment by teameh** [comment]
Haha I just wanted to add an issue for this. I agree. And why not only allow arrays and objects to be passed in? In what case would you like to handle the serialisation yourself?

**Comment by nacmartin** [comment]
Well, nowadays I am using Symfony serializer, but I think that if you were using the JMSSerializer, it was not possible to serialize directly to arrays. Also, it is how React on Rails works (although I don't think users of this bundle need this kind of compatibility with React on Rails).

Anyways, these two points are very weak.
