### ISSUE TITLE
Fix incompatibility with react-on-rails npm package

### ISSUE THREAD

**Issue by teameh** [Limenius/ReactBundle#20]
react-on-rails moved away from hidden divs.. 

> Use `<script type="application/json">` for props and store instead of hidden div [#775](https://github.com/shakacode/react_on_rails/pull/775) 

this bundle needs to be updated as well.. 

(I might be able to work on this next week if you like)

**Comment by teameh** [comment]
~(I might be able to work on this next week if you like)~ working on a proposal now.

**Comment by teameh** [comment]
Haha oh sorry, I wasn't aware of the separation of the renderer into its own package. Made a PR here https://github.com/Limenius/ReactRenderer/pull/1

**Comment by nacmartin** [comment]
Thanks! included in v0.12.0
