### ISSUE TITLE
Fix incompatibility with react-on-rails v7.0.0+

### ISSUE THREAD

**Issue by artempetrovcode** [Limenius/ReactBundle#23]
react-on-rails have moved some properties from script's textContent to its attributes in v7.0.0.
This bundle does not work with react-on-rails v7.0.0+

See [#821](https://github.com/shakacode/react_on_rails/pull/821) and https://github.com/shakacode/react_on_rails/commit/251fa75498a333d11e4c76d06b4065c951b39817#diff-2b02b66a19627ff0da5b8fed749a5742

**Comment by nacmartin** [comment]
Thanks for reporting this, @sttema . I have updated the renderer to the new format in v0.13.0
