### ISSUE TITLE
StaticReactRenderer is not constructed correctly if `limenius_react.react_renderer` service is not defined

### ISSUE THREAD

**Issue by rakelley** [Limenius/ReactBundle#36]
#33 broke compatibility with `default_rendering: "client_side"` configuration, as `\Limenius\ReactRenderer\Twig\ReactRenderExtension::__construct()` blindly calls `\Limenius\ReactRenderer\Renderer\StaticReactRenderer::setRenderer()` without checking if the renderer is null.

Everything works with `server_side` or `both`, or if you have a custom service defined for `limenius_react.react_renderer`, but by default there is no guarantee of such a service existing.

**Comment by rakelley** [comment]
This should actually be on ReactRenderer, sorry

**Comment by WictorT** [comment]
A quick solution to make `client_side` work on Symfony4 is.

In `services.yaml` add under `services` :
```
    limenius_react.react_renderer:
        class: Limenius\ReactRenderer\Renderer\StaticReactRenderer
```
