### ISSUE TITLE
The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "limenius_react" configuration is deprecated

### ISSUE THREAD

**Issue by 4string** [Limenius/ReactBundle#42]
Trying to move to Symfony 5.0. Symfony 4.4 gives deprecation warnings:

The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "limenius_react" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

Thank you!

**Comment by nacmartin** [comment]
there are new versions v5.0.* compatible with sf5 now.
