### ISSUE TITLE
Symfony 5 compatibility ?

### ISSUE THREAD

**Issue by AL-FAW** [Limenius/ReactBundle#44]
Hello,

I have an interest in your project for one of my own, however I'd like to work on Symfony 5, which your project is not compatible with. Are there any plans to make it compatible with it ? If so, do you have an idea as for when it will be available ?

Thanks

**Comment by nacmartin** [comment]
Yes, there are plans to make it compatible. About the estimation, I'd like to say "this week", but it depends on life.

**Comment by AL-FAW** [comment]
Perfect ! Thank you for your (very) quick answer.
