### ISSUE TITLE
Confusion between 'only_serverside' vs 'server_side' 

### ISSUE THREAD

**Issue by teameh** [Limenius/ReactBundle#5]
Why did you choose to use a different shorthand for the default render values used in the services and the ones used when calling the twig function?  Both **[only_serverside](https://github.com/Limenius/ReactBundle/blob/master/Twig/ReactRenderExtension.php#L30)** and **[server_side](https://github.com/Limenius/ReactBundle/blob/master/Twig/ReactRenderExtension.php#L72)** are used for the same thing. Same goes for `only_clientside` and `client_side`. 

I started off doing it right but I mixed them up somewhere along the road and it took me 10 minutes to find out what was going wrong.. It might also be a good idea to throw [here](https://github.com/Limenius/ReactBundle/blob/master/Twig/ReactRenderExtension.php#L42) when none of the render methods are set to true..

**Comment by nacmartin** [comment]
Yes, you are right. And also `only_clientside` should be `only_client_side` I think. I started writing `server_side` and "client_side" but then when thinking about the configuration I thought that it was more explicit to add the `only...` but yes, it would be more consistent to rename the other cases to `only_...` as well

**Comment by teameh** [comment]
Luckily you're still below the v1 mark :sweat_smile: 

I'm not sure if `only_` is better. Once you ever read `both` you know what the other 2 will do right? `client` and `server` might do as well and are nice and short :)

**Comment by nacmartin** [comment]
Ok, if you say so, lets drop the `only_`. If you, that were guessing what the parameters mean, think that it is clear without `only_` your opinion matters more than mine, that was only guessing what would a user understand more easily.

**Comment by teameh** [comment]
Haha yeah, well I'm just another single user.. It's your lib, by all means keep `only_` in if you like :)
